export const data = JSON.parse("{\"key\":\"v-52b9d8b5\",\"path\":\"/react/11-%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96.html\",\"title\":\"性能优化\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"性能优化\",\"order\":11,\"tag\":[\"进阶技巧\",\"性能优化\",\"重渲染\",\"不可变数据\"],\"description\":\"基于 Webpack 等构建工具打包带来的性能优化本章略过，主要讨论 React 内部的针对性优化 虚拟滚动 参考库 虚拟滚动参考react-window (https://github.com/bvaughn/react-window)和react-virtualized (https://github.com/bvaughn/react-virtu...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/react/11-%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"前端-navigation\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"性能优化\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"基于 Webpack 等构建工具打包带来的性能优化本章略过，主要讨论 React 内部的针对性优化 虚拟滚动 参考库 虚拟滚动参考react-window (https://github.com/bvaughn/react-window)和react-virtualized (https://github.com/bvaughn/react-virtu...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"tokobin\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"进阶技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"性能优化\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"重渲染\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"不可变数据\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"性能优化\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"tokobin\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"虚拟滚动\",\"slug\":\"虚拟滚动\",\"link\":\"#虚拟滚动\",\"children\":[{\"level\":3,\"title\":\"参考库\",\"slug\":\"参考库\",\"link\":\"#参考库\",\"children\":[]},{\"level\":3,\"title\":\"原理\",\"slug\":\"原理\",\"link\":\"#原理\",\"children\":[]}]},{\"level\":2,\"title\":\"rerender 优化\",\"slug\":\"rerender-优化\",\"link\":\"#rerender-优化\",\"children\":[{\"level\":3,\"title\":\"shouldComponentUpdate\",\"slug\":\"shouldcomponentupdate\",\"link\":\"#shouldcomponentupdate\",\"children\":[]},{\"level\":3,\"title\":\"PureComponent\",\"slug\":\"purecomponent\",\"link\":\"#purecomponent\",\"children\":[]},{\"level\":3,\"title\":\"memo\",\"slug\":\"memo\",\"link\":\"#memo\",\"children\":[]},{\"level\":3,\"title\":\"useMemo\",\"slug\":\"usememo\",\"link\":\"#usememo\",\"children\":[]},{\"level\":3,\"title\":\"useCallback\",\"slug\":\"usecallback\",\"link\":\"#usecallback\",\"children\":[]}]},{\"level\":2,\"title\":\"不可变数据操作\",\"slug\":\"不可变数据操作\",\"link\":\"#不可变数据操作\",\"children\":[]}],\"readingTime\":{\"minutes\":4.78,\"words\":1435},\"filePathRelative\":\"react/11-性能优化.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
