export const data = JSON.parse("{\"key\":\"v-1b954120\",\"path\":\"/react/13-react%E7%94%9F%E6%80%81/5-redux-toolkit.html\",\"title\":\"Redux-toolkit\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Redux-toolkit\",\"order\":5,\"tag\":[\"全局状态管理\",\"Redux-toolkit\"],\"description\":\"redux-toolkit是目前 redux 官方推荐的编写 redux 逻辑的方法，针对 redux 本身创建 store 繁琐、样板代码过多、依赖外部库等问题进行了优化，调用 API 更加简单快捷 redux 最新版本也已经标记 createStore 方法为弃用，推荐使用 redux-toolkit 入口文件 没有变化 store.js conf...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/react/13-react%E7%94%9F%E6%80%81/5-redux-toolkit.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"前端-navigation\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Redux-toolkit\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"redux-toolkit是目前 redux 官方推荐的编写 redux 逻辑的方法，针对 redux 本身创建 store 繁琐、样板代码过多、依赖外部库等问题进行了优化，调用 API 更加简单快捷 redux 最新版本也已经标记 createStore 方法为弃用，推荐使用 redux-toolkit 入口文件 没有变化 store.js conf...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"tokobin\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"全局状态管理\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Redux-toolkit\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Redux-toolkit\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"tokobin\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"入口文件\",\"slug\":\"入口文件\",\"link\":\"#入口文件\",\"children\":[]},{\"level\":2,\"title\":\"store.js\",\"slug\":\"store-js\",\"link\":\"#store-js\",\"children\":[]},{\"level\":2,\"title\":\"actions&reducers\",\"slug\":\"actions-reducers\",\"link\":\"#actions-reducers\",\"children\":[]},{\"level\":2,\"title\":\"视图组件调用\",\"slug\":\"视图组件调用\",\"link\":\"#视图组件调用\",\"children\":[]},{\"level\":2,\"title\":\"进阶1：副作用处理\",\"slug\":\"进阶1-副作用处理\",\"link\":\"#进阶1-副作用处理\",\"children\":[]},{\"level\":2,\"title\":\"进阶2：使用 selector 缓存\",\"slug\":\"进阶2-使用-selector-缓存\",\"link\":\"#进阶2-使用-selector-缓存\",\"children\":[]},{\"level\":2,\"title\":\"进阶3：范式化state\",\"slug\":\"进阶3-范式化state\",\"link\":\"#进阶3-范式化state\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":4.12,\"words\":1237},\"filePathRelative\":\"react/13-react生态/5-redux-toolkit.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
